---
- hosts: local
  connection: local
  gather_facts: false
  vars:
    instance_type: t2.micro
    security_group: im-webserver
    image: ami-c7ab5fa0
    keypair: imran-key
    region: eu-west-2
    count: 1
    env: lab-01
  vars_files:
    - aws_pass.yml

  tasks:
    - import_tasks: roles/common/tasks/init-ec2.yml

- hosts: webservers
  gather_facts: false
  remote_user: ubuntu
  become: true

  tasks:
    - import_tasks: roles/webservers/tasks/install-nginx.yml

  handlers:
    - include: roles/webservers/handlers/main.yml
