---
- hosts: local
  connection: local
  gather_facts: false
  vars:
    instance_type: t2.micro
    security_group: im-webserver
    image: ami-c7ab5fa0
    keypair: imran-key
    region: eu-west-2
    count: 1
    env: lab-01
  vars_files:
    - aws_pass.yml

  roles:
  - init-ec2

- hosts: webservers
  gather_facts: true
  remote_user: ubuntu
  become: true

  roles:
  - webservers
  - geerlingguy.ntp
